Feat/boom task workspace
CUSW-chula/cusw-backend pull request #2
Opened 2024-10-26 14:57 UTC by bypkt-bk

2024-10-27 19:54 UTC, bypkt-bk commented
### Emoji
[ controllers, models and services ]

- [x] updateEmojiByTaskId
- [x] getAllEmojiByTaskId
- [x] addEmojiOnTask

2024-11-01 17:10 UTC, bunnybunbun37204 requested changes
- แก้เรื่อง format ของการส่ง response ใน controller
-  เช็คเรื่องดีเทลอื่นๆ (minor ไม่มีไรมาก)

2024-11-01 17:10 UTC, bunnybunbun37204 commented on src/controllers/tasks.controller.ts
> +					body: { error: error },
ควรเขียนโดย format
```
try {
				const files = await fileService.getFileByTaskId(id);
				if (!files) {
					return Response.json("file not found", { status: 404 });
				}
				return files;
			} catch (_error) {
				const error = _error as Error;
				return Response.json(error.message, { status: 500 });
			}
```

2024-11-01 17:10 UTC, bunnybunbun37204 commented on src/services/tasks.service.ts
> +	User,
อันไหนไม่ใช้ลบด้วย

2024-11-01 17:20 UTC, bunnybunbun37204 requested changes

2024-11-01 17:20 UTC, bunnybunbun37204 commented on src/services/tasks.service.ts
> +
ทำระบบ cache ไว้ด้วยนะ

2024-11-05 16:55 UTC, merged