feat(activity-logs): first time sex kub
CUSW-chula/cusw-backend pull request #6
Opened 2024-10-30 17:27 UTC by Romeliette

2024-10-30 18:02 UTC, Romeliette commented
ตรวจด้วยครับเกม

2024-11-01 17:19 UTC, bunnybunbun37204 requested changes

2024-11-01 17:19 UTC, bunnybunbun37204 commented on prisma/schema.prisma
เติม enum ให้ครบ

2024-11-01 17:19 UTC, bunnybunbun37204 commented on src/controllers/activity-logs.controllers.ts
> +			};
เปลี่ยนวิธีเขียน return error เป็น
```
			try {
				const files = await fileService.getFileByTaskId(id);
				if (!files) {
					return Response.json("file not found", { status: 404 });
				}
				return files;
			} catch (_error) {
				const error = _error as Error;
				return Response.json(error.message, { status: 500 });
			}
		},
```

2024-11-01 17:19 UTC, bunnybunbun37204 commented on src/services/activity-logs.service.ts
> +	}
ทำระบบ cache ไว้ด้วยก็ดี

2024-11-05 11:38 UTC, Romeliette commented
+ update Enum
+ add code to receive log from tag and file controller
+ add cache into log services
+ edit try/catch error in log controller
+ add log api

2024-11-05 15:09 UTC, merged